#This file sets usr_path.mk variables to cmake variables that can later be used in CMakeLists.txt

set(WORKSPACE_DIR $ENV{WORKSPACE_DIR})
set(BUILD_DIR $ENV{BUILD_DIR})

set(C_DIR $ENV{C_DIR})
set(TEST_DIR $ENV{TEST_DIR})
set(TESTS_FRAMEWORKS_DIR $ENV{TESTS_FRAMEWORKS_DIR})
set(CMOCK_DIR $ENV{CMOCK_DIR})
set(CMOCKA_DIR $ENV{CMOCKA_DIR})
set(CMOCKA_BUILD_DIR $ENV{CMOCKA_BUILD_DIR})

set(ADVANCED_MATH_DIR $ENV{ADVANCED_MATH_DIR})
set(ADVANCED_MATH_DIR_SRC $ENV{ADVANCED_MATH_DIR_SRC})
set(ADVANCED_MATH_DIR_INC $ENV{ADVANCED_MATH_DIR_INC})

set(C_MOCK_BUILD_DIR $ENV{C_MOCK_BUILD_DIR})
set(UNITY_DIR $ENV{UNITY_DIR})
set(UNITY_DIR_SRC $ENV{UNITY_DIR_SRC})
set(BUILD_TU_TEST_DIR $ENV{BUILD_TU_TEST_DIR})
set(BUILD_TEST_DIR $ENV{BUILD_TEST_DIR})

set(RUN_MODE $ENV{RUN_MODE})

if(APPLE)
    set(CMOCKA_LIB libcmocka.dylib)
else()
    set(CMOCKA_LIB libcmocka.so)
endif()